export const LOCALSTORAGE_ACTIONS = {
  LOGIN_USER_DATA: 'LOGIN_USER_DATA',
  LOGIN_USER_TOKEN: 'LOGIN_USER_TOKEN',
};

export const DATA_ACTIONS = {
  DATA_ATTEMPT: 'DATA_ATTEMPT',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_FAILED: 'DATA_FAILED',
};

export const USER_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
};
